package com.playona.api.domain.track.service;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.playona.api.domain.track.repository.TrackRepository;
import com.playona.api.domain.track.entity.Track;
import com.playona.api.domain.platform.entity.Platform;
import com.playona.api.global.exception.GlobalExceptionHandler;
import java.util.Map;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpStatus;
import org.springframework.test.util.ReflectionTestUtils;
import org.springframework.web.reactive.function.client.ClientResponse;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.publisher.Mono;

class YoutubeTrackServiceTest {

  @Test
  void usesExplicitTopicReleaseDateInsteadOfUtcPublicationDate() throws Exception {
    String description = "Provided to YouTube by Label\nReleased on: 2026-03-30\nAuto-generated by YouTube.";
    String published = "2026-03-29T15:04:06Z";
    assertEquals(java.time.LocalDate.of(2026, 3, 30),
        YoutubeTrackService.sourceReleaseDate("Artist - Topic", description, published));
    assertEquals(java.time.LocalDate.of(2026, 3, 29),
        YoutubeTrackService.sourceReleaseDate("Fan Upload", description, published));
    assertEquals(java.time.LocalDate.of(2026, 3, 29),
        YoutubeTrackService.sourceReleaseDate("Artist - Topic", description.replace("2026-03-30", "2026-02-31"), published));
    var apple = mock(AppleTrackService.class);
    var service = new YoutubeTrackService(mock(TrackRepository.class), apple);
    String response = new ObjectMapper().writeValueAsString(Map.of("items", List.of(Map.of(
        "snippet", Map.of("title", "Morning", "channelTitle", "Artist - Topic", "description", description,
            "categoryId", "10", "publishedAt", published), "contentDetails", Map.of("duration", "PT3M")))));
    ReflectionTestUtils.setField(service, "webClient", jsonClient(response));
    Track source = service.getTrackFromUrl("https://youtu.be/testvideo01");
    assertEquals(java.time.LocalDate.of(2026, 3, 30), source.getReleaseDate());
    verify(apple).enrichTopicMetadata(source);
  }

  @Test
  void usesExplicitCreatorCreditsAndTranslationsForBothSourceAndSearch() throws Exception {
    for (String[] names : List.of(
        new String[]{"朝", "Morning", "月", "Moon", "歌手", "Singer"},
        new String[]{"メズマライザー", "Mesmerizer", "サツキ", "32ki", "初音ミク・重音テトSV", "Hatsune Miku＆Kasane Teto"})) {
      Map video = creditedVideo(names, names[2]);
      var metadata = YoutubeTrackService.extractSourceMetadata(video);
      assertEquals(names[0] + " (" + names[1] + ")", metadata.title());
      assertEquals(names[2] + " (" + names[3] + ")", metadata.artist());
      assertNull(YoutubeTrackService.extractSourceMetadata(creditedVideo(names, "Unrelated Uploader")));
      assertNull(YoutubeTrackService.extractSourceMetadata(
          names[0] + " / " + names[4] + " - " + names[1], names[2]));

      TrackRepository repository = mock(TrackRepository.class);
      YoutubeTrackService service = new YoutubeTrackService(repository, mock(AppleTrackService.class));
      ObjectMapper mapper = new ObjectMapper();
      String details = mapper.writeValueAsString(Map.of("items", List.of(video)));
      String search = mapper.writeValueAsString(Map.of("items", List.of(Map.of(
          "id", Map.of("videoId", "testvideo01"), "snippet", video.get("snippet")))));
      ReflectionTestUtils.setField(service, "webClient", WebClient.builder()
          .baseUrl("https://www.googleapis.com")
          .exchangeFunction(request -> Mono.just(ClientResponse.create(HttpStatus.OK)
              .header("Content-Type", "application/json")
              .body(request.url().getPath().endsWith("/search") ? search : details).build())).build());
      Track source = service.getTrackFromUrl("https://youtu.be/testvideo01");
      assertEquals(metadata.title(), source.getTitle());
      assertEquals(metadata.artist(), source.getArtist());
      assertEquals(157000, source.getDurationMs());

      Track catalog = new Track(names[0], names[3], null, "https://example.com/track");
      catalog.setDurationMs(156972);
      assertEquals("https://music.youtube.com/watch?v=testvideo01",
          service.searchTrack(catalog, mock(Platform.class)).getUrl());
    }
  }

  @Test
  void doesNotTreatUnrelatedDescriptionTextOrDifferentVocalCreditsAsAliases() {
    Map video = Map.of("snippet", Map.of("title", "朝 / 別の歌手 - Morning", "channelTitle", "月",
        "description", "■Music / 月\n■Vocal / 歌手"));
    assertNull(YoutubeTrackService.extractSourceMetadata(video));
    video = Map.of("snippet", Map.of("title", "朝 / 歌手 - Morning", "channelTitle", "月",
        "description", "Recommended Music / 月\n■Vocal / 歌手"));
    assertNull(YoutubeTrackService.extractSourceMetadata(video));
  }

  private Map creditedVideo(String[] names, String channel) {
    return Map.of("id", "testvideo01", "snippet", Map.of(
        "title", names[0] + " / " + names[4] + " - " + names[1], "channelTitle", channel,
        "description", "■Music / " + names[2] + "\n■Vocal / " + names[4],
        "categoryId", "10", "liveBroadcastContent", "none"),
        "contentDetails", Map.of("duration", "PT2M37S"),
        "localizations", Map.of("en", Map.of("title", names[1] + " / " + names[5],
            "description", "■Music / " + names[3] + "\n■Vocal / " + names[5])));
  }

  @Test
  void rejectsCopiedTitleAndDurationFromUnmatchedUploader() throws Exception {
    YoutubeTrackService service = new YoutubeTrackService(mock(TrackRepository.class), mock(AppleTrackService.class));
    Track track = new Track("Morning", "Original Artist", null, "https://example.com/track");
    track.setDurationMs(180000);
    ObjectMapper mapper = new ObjectMapper();
    for (String channel : List.of("Unrelated Uploader", "Original Artist - Topic")) {
      String search = mapper.writeValueAsString(Map.of("items", List.of(Map.of(
          "id", Map.of("videoId", "candidate"),
          "snippet", Map.of("title", "Morning", "channelTitle", channel)))));
      String details = mapper.writeValueAsString(Map.of("items", List.of(Map.of(
          "id", "candidate", "contentDetails", Map.of("duration", "PT3M")))));
      ReflectionTestUtils.setField(service, "webClient", WebClient.builder()
          .baseUrl("https://www.googleapis.com")
          .exchangeFunction(request -> Mono.just(ClientResponse.create(HttpStatus.OK)
              .header("Content-Type", "application/json")
              .body(request.url().getPath().endsWith("/search") ? search : details).build())).build());
      var result = service.searchTrack(track, mock(Platform.class));
      if (channel.equals("Unrelated Uploader")) assertNull(result);
      else assertEquals("https://music.youtube.com/watch?v=candidate", result.getUrl());
    }
  }

  @Test
  void acceptsOfficialLyricVideoOnArtistChannelButRejectsFanUploadsAndOtherVersions() throws Exception {
    String title = "Mrs. GREEN APPLE「soFt-dRink」Official Lyric Video";
    assertFalse(YoutubeTrackService.isUnsupportedSourceVideo(title, "Mrs. GREEN APPLE"));
    assertTrue(YoutubeTrackService.isUnsupportedSourceVideo(title, "Fan Lyrics"));
    assertTrue(YoutubeTrackService.isUnsupportedSourceVideo(
        "Mrs. GREEN APPLE - soFt-dRink Lyrics", "Mrs. GREEN APPLE"));
    assertTrue(YoutubeTrackService.isUnsupportedSourceVideo(
        "Mrs. GREEN APPLE「soFt-dRink (Live)」Official Lyric Video", "Mrs. GREEN APPLE"));
    assertEquals(new YoutubeTrackService.SourceMetadata("soFt-dRink", "Mrs. GREEN APPLE"),
        YoutubeTrackService.extractSourceMetadata(title, "Mrs. GREEN APPLE"));

    TrackRepository repository = mock(TrackRepository.class);
    YoutubeTrackService service = new YoutubeTrackService(repository, mock(AppleTrackService.class));
    String response = new ObjectMapper().writeValueAsString(Map.of("items", List.of(Map.of(
        "snippet", Map.of("categoryId", "10", "liveBroadcastContent", "none",
            "title", title, "channelTitle", "Mrs. GREEN APPLE", "description", ""),
        "contentDetails", Map.of("duration", "PT3M")))));
    ReflectionTestUtils.setField(service, "webClient", jsonClient(response));
    Track result = service.getTrackFromUrl("https://music.youtube.com/watch?v=vt9YVvYFitg&si=example");
    assertEquals("soFt-dRink", result.getTitle());
    assertEquals("Mrs. GREEN APPLE", result.getArtist());
    verify(repository).save(result);
  }

  private static final String COMPILATION_DESCRIPTION = """
      썸네일: 핀터레스트
      0:00 Je te laisserai des mots - Patrick Watson
      2:42 rises the moon - Liana Flores
      5:25 Here Comes a Thought(slowed) - Steven Universe
      9:13 Space Song - BeachHouse
      14:33 Roslyn - Bon Iver & St. Vincent
      """;

  @Test
  void detectsCompilationTitlesAndMultipleSongTimestamps() {
    assertTrue(YoutubeTrackService.isMusicCompilation("꿈", COMPILATION_DESCRIPTION));
    assertTrue(YoutubeTrackService.isMusicCompilation("𝐏𝐥𝐚𝐲𝐥𝐢𝐬𝐭 | 여름", null));
    assertTrue(YoutubeTrackService.isMusicCompilation("잔잔한 음악 모음", null));
    assertTrue(YoutubeTrackService.isMusicCompilation("Artist - Full Album", null));
    assertTrue(YoutubeTrackService.isMusicCompilation("꿈", "Tracklist\n0:00 First song\n3:00 Second song"));
  }

  @Test
  void acceptsSingleSongsWithoutTreatingChaptersOrPromotionalLinksAsCompilations() {
    assertFalse(YoutubeTrackService.isMusicCompilation(null, null));
    assertFalse(YoutubeTrackService.isMusicCompilation("아이유 - 밤편지 Official Music Video",
        "My playlist: https://youtube.com/playlist?list=example\n0:00 Intro\n0:30 Verse\n1:00 Chorus"));
    assertFalse(YoutubeTrackService.isMusicCompilation("꿈", "0:00 Song - Artist"));
    assertFalse(YoutubeTrackService.isMusicCompilation("꿈", "0:00 Song - Artist\n0:00 Song - Artist"));
    assertFalse(YoutubeTrackService.isMusicCompilation("꿈", "0:00 Song - Artist\n3:00 Song - Artist"));
  }

  @Test
  void extractsOnlyExplicitArtistTitleFormatsWithoutDiscardingPartsOfTitles() {
    assertEquals(new YoutubeTrackService.SourceMetadata("밤편지", "IU"),
        YoutubeTrackService.extractSourceMetadata("[MV] IU - 밤편지", "1theK"));
    assertEquals(new YoutubeTrackService.SourceMetadata("밤편지", "아이유"),
        YoutubeTrackService.extractSourceMetadata("아이유 - 밤편지 Official Music Video", "1theK"));
    assertEquals(new YoutubeTrackService.SourceMetadata("문득(eternal)", "윤지영(Yoon Jiyoung)"),
        YoutubeTrackService.extractSourceMetadata(
            "[MV] 윤지영(Yoon Jiyoung) - 문득(eternal) / Official Music Video", "POCLANOS"));
    assertEquals(new YoutubeTrackService.SourceMetadata("밤편지 (Live)", "아이유"),
        YoutubeTrackService.extractSourceMetadata("아이유 - 밤편지 (Live)", "아이유 - Topic"));
    assertNull(YoutubeTrackService.extractSourceMetadata("밤편지", "가사 채널"));
    assertEquals(new YoutubeTrackService.SourceMetadata("Square's dream (네모의 꿈)", "Artist"),
        YoutubeTrackService.extractSourceMetadata("Square's dream (네모의 꿈)", "Artist - Topic"));
  }

  @Test
  void refreshesExistingYoutubeMetadataBeforeReusingIt() throws Exception {
    TrackRepository repository = mock(TrackRepository.class);
    Track existing = new Track("MV", "1theK", null, "https://music.youtube.com/watch?v=15DI60dGMMo");
    when(repository.findFirstBySourceUrl(existing.getSourceUrl())).thenReturn(Optional.of(existing));
    YoutubeTrackService service = new YoutubeTrackService(repository, mock(AppleTrackService.class));
    String response = new ObjectMapper().writeValueAsString(Map.of("items", List.of(Map.of(
        "snippet", Map.of("categoryId", "10", "liveBroadcastContent", "none",
            "title", "IU - 밤편지", "channelTitle", "1theK", "description", ""),
        "contentDetails", Map.of("duration", "PT4M13S")))));
    ReflectionTestUtils.setField(service, "webClient", jsonClient(response));

    Track refreshed = service.getTrackFromUrl(existing.getSourceUrl());

    assertSame(existing, refreshed);
    assertEquals("밤편지", refreshed.getTitle());
    assertEquals("IU", refreshed.getArtist());
    assertEquals(253_000, refreshed.getDurationMs());
    verify(repository).save(existing);
  }

  @Test
  void rejectsReportedVideoBeforeDatabaseAccessAndReturnsBadRequestMessage() throws Exception {
    TrackRepository repository = mock(TrackRepository.class);
    YoutubeTrackService service = new YoutubeTrackService(repository, mock(AppleTrackService.class));
    String response = new ObjectMapper().writeValueAsString(Map.of("items", List.of(Map.of(
        "snippet", Map.of("categoryId", "10", "liveBroadcastContent", "none",
            "title", "꿈", "channelTitle", "Sea Pearl", "description", COMPILATION_DESCRIPTION),
        "contentDetails", Map.of("duration", "PT19M43S")))));
    ReflectionTestUtils.setField(service, "webClient", jsonClient(response));
    ReflectionTestUtils.setField(service, "apiKey", "test-key");

    IllegalArgumentException error = assertThrows(IllegalArgumentException.class,
        () -> service.getTrackFromUrl("https://music.youtube.com/watch?v=15DI60dGMMo"));

    verifyNoInteractions(repository);
    var result = new GlobalExceptionHandler().handleIllegalArgument(error);
    assertEquals(HttpStatus.BAD_REQUEST, result.getStatusCode());
    assertFalse(result.getBody().isSuccess());
    assertEquals("해당 링크는 음악 모음 영상이므로 통합 링크를 만들 수 없습니다.", result.getBody().getMessage());
  }

  @Test
  void acceptsOnlyNonLiveMusicCategorySourceVideos() {
    assertTrue(YoutubeTrackService.isAcceptedSourceVideo("10", "none"));
    assertTrue(YoutubeTrackService.isAcceptedSourceVideo("24", "none"));
    assertFalse(YoutubeTrackService.isAcceptedSourceVideo("10", "live"));
    assertFalse(YoutubeTrackService.isAcceptedSourceVideo("22", "none"));
  }

  @Test
  void requiresCandidateTitleToMatchTrackTitle() {
    assertTrue(TrackMatchVerifier.hasMatchingTitleAndArtist("밤편지", "아이유", "밤편지", "아이유"));
    assertFalse(TrackMatchVerifier.hasMatchingTitleAndArtist("밤편지", "아이유", "아이유 좋은 날", "아이유"));
  }

  @Test
  void rejectsCandidateWithIncompatibleDuration() {
    assertTrue(YoutubeTrackService.hasCompatibleDuration(210_000, 220_000L));
    assertFalse(YoutubeTrackService.hasCompatibleDuration(210_000, 241_000L));
  }

  @Test
  void requiresKnownDurationsAndDoesNotTreatWordFragmentsAsNoise() {
    assertFalse(YoutubeTrackService.hasCompatibleDuration(210_000, null));
    assertTrue(YoutubeTrackService.hasCompatibleDuration(210_000, 235_000L));
  }

  private WebClient jsonClient(String response) {
    return WebClient.builder().exchangeFunction(request -> Mono.just(
        ClientResponse.create(HttpStatus.OK).header("Content-Type", "application/json")
            .body(response).build())).build();
  }
}
