package com.playona.api.domain.track.service;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.playona.api.domain.track.repository.TrackRepository;
import com.playona.api.domain.track.entity.Track;
import com.playona.api.domain.platform.entity.Platform;
import com.playona.api.global.exception.GlobalExceptionHandler;
import java.util.Map;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpStatus;
import org.springframework.test.util.ReflectionTestUtils;
import org.springframework.web.reactive.function.client.ClientResponse;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.publisher.Mono;

class YoutubeTrackServiceTest {
  @Test
  void verifiesRegionalMusicAliasesAgainstTheCanonicalRecording() {
    Track source = new Track("Let's Say Goodbye", "Parc Jae Jung", null, "https://music.youtube.com/watch?v=original001");
    source.setDurationMs(244000);
    source.setReleaseDate(java.time.LocalDate.of(2023, 4, 20));
    String html = """
        <meta property="og:url" content="https://music.youtube.com/watch?v=regional001">
        <meta property="og:title" content="헤어지자 말해요">
        <meta property="og:description" content="박재정">
        <meta property="og:video:tag" content="Let’s Say Goodbye">
        <meta property="og:video:tag" content="Parc Jae Jung">
        <meta property="og:video:tag" content="헤어지자 말해요">
        <meta property="og:video:tag" content="박재정">
        """;
    Map snippet = Map.of("title", "Let’s Say Goodbye (헤어지자 말해요)", "channelTitle", "Parc Jae Jung - Topic",
        "description", "Provided to YouTube by Distributor\nReleased on: 2023-04-20\nAuto-generated by YouTube.",
        "publishedAt", "2023-04-20T00:00:00Z");
    Map canonical = Map.of("id", "regional001", "snippet", snippet, "contentDetails", Map.of("duration", "PT4M4S"));
    assertEquals(new YoutubeTrackService.SourceMetadata("헤어지자 말해요", "박재정"),
        YoutubeTrackService.localizedMusicMetadata(source, html, canonical));
    assertNull(YoutubeTrackService.localizedMusicMetadata(source, html.replace("regional001", "unrelated01"), canonical));
    assertNull(YoutubeTrackService.localizedMusicMetadata(source, html.replace("Parc Jae Jung", "Other Artist"), canonical));
    assertNull(YoutubeTrackService.localizedMusicMetadata(source, html.replace("Let’s Say Goodbye", "Different Song"), canonical));
    assertNull(YoutubeTrackService.localizedMusicMetadata(source, html, null));
    source.setDurationMs(260000);
    assertNull(YoutubeTrackService.localizedMusicMetadata(source, html, canonical));
    source.setDurationMs(244000);
    source.setReleaseDate(java.time.LocalDate.of(2024, 4, 20));
    assertNull(YoutubeTrackService.localizedMusicMetadata(source, html, canonical));
    source.setReleaseDate(java.time.LocalDate.of(2023, 4, 20));
    source.setTitle("Let's Say Goodbye (Live)");
    assertNull(YoutubeTrackService.localizedMusicMetadata(source, html, canonical));
  }

  @Test
  void corroboratesDistributorCreditsAndKeepsLanguageVersionsSeparate() throws Exception {
    for (String scenario : List.of("distributor", "no-credits", "wrong-date", "wrong-artist", "english", "wrong-language-date")) {
      boolean english = scenario.contains("language") || scenario.equals("english");
      String artist = "Artist";
      String title = english ? "Artist / Morning (「朝」English Ver. )" : "[MV] Artist - Morning / Official Music Video";
      String channel = english ? "Artist" : "Distributor";
      String description = scenario.equals("no-credits") ? "" : "Artist - Morning / Official Music Video";
      if (scenario.equals("wrong-artist")) description = "Other - Morning / Official Music Video";
      String date = scenario.contains("date") ? "2025-04-01T00:00:00Z" : "2025-05-01T00:00:00Z";
      var snippet = Map.of("title", title, "channelTitle", channel, "description", description, "publishedAt", date);
      var mapper = new ObjectMapper();
      String search = mapper.writeValueAsString(Map.of("items", List.of(Map.of("id", Map.of("videoId", "testvideo01"), "snippet", snippet))));
      String details = mapper.writeValueAsString(Map.of("items", List.of(Map.of("id", "testvideo01", "snippet", snippet,
          "contentDetails", Map.of("duration", "PT3M5S")))));
      var service = new YoutubeTrackService(mock(TrackRepository.class), mock(AppleTrackService.class));
      ReflectionTestUtils.setField(service, "webClient", WebClient.builder().baseUrl("https://www.googleapis.com")
          .exchangeFunction(request -> Mono.just(ClientResponse.create(HttpStatus.OK).header("Content-Type", "application/json")
              .body(request.url().getPath().endsWith("/search") ? search : details).build())).build());
      Track source = new Track("Morning", artist, null, "https://example.com/song");
      source.setDurationMs(180000);
      source.setReleaseDate(java.time.LocalDate.of(2025, 5, 1));
      var result = service.searchTrack(source, mock(Platform.class));
      if (scenario.equals("distributor") || scenario.equals("english")) {
        assertEquals("https://music.youtube.com/watch?v=testvideo01", result.getUrl());
      } else assertNull(result, scenario);
    }
  }

  @Test
  void parsesQuotedTitlesAndWrappedOfficialLabelsWithoutAcceptingFanLyrics() {
    assertEquals(new YoutubeTrackService.SourceMetadata("Love wins all", "IU"),
        YoutubeTrackService.extractSourceMetadata("IU 'Love wins all' MV", "이지금 [IU Official]"));
    assertEquals(new YoutubeTrackService.SourceMetadata("Hello", "Adele"),
        YoutubeTrackService.extractSourceMetadata("Adele - Hello (Official Music Video)", "Adele"));
    assertEquals(new YoutubeTrackService.SourceMetadata("Shape Of You", "Ed Sheeran"),
        YoutubeTrackService.extractSourceMetadata("Ed Sheeran - Shape Of You [Official Lyric Video]", "Ed Sheeran"));
    assertFalse(YoutubeTrackService.isUnsupportedSourceVideo(
        "Ed Sheeran - Shape Of You [Official Lyric Video]", "EdSheeranVEVO"));
    assertTrue(YoutubeTrackService.isUnsupportedSourceVideo(
        "Ed Sheeran - Shape Of You [Official Lyric Video]", "Fan Channel"));
    assertTrue(YoutubeTrackService.isUnsupportedSourceVideo(
        "Artist - Song (Live) [Official Lyric Video]", "Artist"));
    assertEquals(new YoutubeTrackService.SourceMetadata("Ditto", "NewJeans (뉴진스)"),
        YoutubeTrackService.extractSourceMetadata("NewJeans (뉴진스) 'Ditto' Performance Video", "NewJeans"));
  }

  @Test
  void usesExplicitTopicReleaseDateInsteadOfUtcPublicationDate() throws Exception {
    String description = "Provided to YouTube by Label\nReleased on: 2026-03-30\nAuto-generated by YouTube.";
    String published = "2026-03-29T15:04:06Z";
    assertEquals(java.time.LocalDate.of(2026, 3, 30),
        YoutubeTrackService.sourceReleaseDate("Artist - Topic", description, published));
    assertEquals(java.time.LocalDate.of(2026, 3, 29),
        YoutubeTrackService.sourceReleaseDate("Fan Upload", description, published));
    assertEquals(java.time.LocalDate.of(2026, 3, 29),
        YoutubeTrackService.sourceReleaseDate("Artist - Topic", description.replace("2026-03-30", "2026-02-31"), published));
    var apple = mock(AppleTrackService.class);
    var service = new YoutubeTrackService(mock(TrackRepository.class), apple);
    String response = new ObjectMapper().writeValueAsString(Map.of("items", List.of(Map.of(
        "snippet", Map.of("title", "Morning", "channelTitle", "Artist - Topic", "description", description,
            "categoryId", "10", "publishedAt", published), "contentDetails", Map.of("duration", "PT3M")))));
    ReflectionTestUtils.setField(service, "webClient", jsonClient(response));
    Track source = service.getTrackFromUrl("https://youtu.be/testvideo01");
    assertEquals(java.time.LocalDate.of(2026, 3, 30), source.getReleaseDate());
    verify(apple).enrichTopicMetadata(source);
  }

  @Test
  void usesExplicitCreatorCreditsAndTranslationsForBothSourceAndSearch() throws Exception {
    for (String[] names : List.of(
        new String[]{"朝", "Morning", "月", "Moon", "歌手", "Singer"},
        new String[]{"メズマライザー", "Mesmerizer", "サツキ", "32ki", "初音ミク・重音テトSV", "Hatsune Miku＆Kasane Teto"})) {
      Map video = creditedVideo(names, names[2]);
      var metadata = YoutubeTrackService.extractSourceMetadata(video);
      assertEquals(names[0] + " (" + names[1] + ")", metadata.title());
      assertEquals(names[2] + " (" + names[3] + ")", metadata.artist());
      assertNull(YoutubeTrackService.extractSourceMetadata(creditedVideo(names, "Unrelated Uploader")));
      assertNull(YoutubeTrackService.extractSourceMetadata(
          names[0] + " / " + names[4] + " - " + names[1], names[2]));

      TrackRepository repository = mock(TrackRepository.class);
      YoutubeTrackService service = new YoutubeTrackService(repository, mock(AppleTrackService.class));
      ObjectMapper mapper = new ObjectMapper();
      String details = mapper.writeValueAsString(Map.of("items", List.of(video)));
      String search = mapper.writeValueAsString(Map.of("items", List.of(Map.of(
          "id", Map.of("videoId", "testvideo01"), "snippet", video.get("snippet")))));
      ReflectionTestUtils.setField(service, "webClient", WebClient.builder()
          .baseUrl("https://www.googleapis.com")
          .exchangeFunction(request -> Mono.just(ClientResponse.create(HttpStatus.OK)
              .header("Content-Type", "application/json")
              .body(request.url().getPath().endsWith("/search") ? search : details).build())).build());
      Track source = service.getTrackFromUrl("https://youtu.be/testvideo01");
      assertEquals(metadata.title(), source.getTitle());
      assertEquals(metadata.artist(), source.getArtist());
      assertEquals(157000, source.getDurationMs());

      Track catalog = new Track(names[0], names[3], null, "https://example.com/track");
      catalog.setDurationMs(156972);
      assertEquals("https://music.youtube.com/watch?v=testvideo01",
          service.searchTrack(catalog, mock(Platform.class)).getUrl());
      assertEquals("testvideo01", service.searchCandidates(catalog).get(0).id());
    }
  }

  @Test
  void doesNotTreatUnrelatedDescriptionTextOrDifferentVocalCreditsAsAliases() {
    Map video = Map.of("snippet", Map.of("title", "朝 / 別の歌手 - Morning", "channelTitle", "月",
        "description", "■Music / 月\n■Vocal / 歌手"));
    assertNull(YoutubeTrackService.extractSourceMetadata(video));
    video = Map.of("snippet", Map.of("title", "朝 / 歌手 - Morning", "channelTitle", "月",
        "description", "Recommended Music / 月\n■Vocal / 歌手"));
    assertNull(YoutubeTrackService.extractSourceMetadata(video));
  }

  private Map creditedVideo(String[] names, String channel) {
    return Map.of("id", "testvideo01", "snippet", Map.of(
        "title", names[0] + " / " + names[4] + " - " + names[1], "channelTitle", channel,
        "description", "■Music / " + names[2] + "\n■Vocal / " + names[4],
        "categoryId", "10", "liveBroadcastContent", "none"),
        "contentDetails", Map.of("duration", "PT2M37S"),
        "localizations", Map.of("en", Map.of("title", names[1] + " / " + names[5],
            "description", "■Music / " + names[3] + "\n■Vocal / " + names[5])));
  }

  @Test
  void rejectsCopiedTitleAndDurationFromUnmatchedUploader() throws Exception {
    YoutubeTrackService service = new YoutubeTrackService(mock(TrackRepository.class), mock(AppleTrackService.class));
    Track track = new Track("Morning", "Original Artist", null, "https://example.com/track");
    track.setDurationMs(180000);
    ObjectMapper mapper = new ObjectMapper();
    for (String channel : List.of("Unrelated Uploader", "Original Artist - Topic")) {
      String search = mapper.writeValueAsString(Map.of("items", List.of(Map.of(
          "id", Map.of("videoId", "candidate"),
          "snippet", Map.of("title", "Morning", "channelTitle", channel)))));
      String details = mapper.writeValueAsString(Map.of("items", List.of(Map.of(
          "id", "candidate", "contentDetails", Map.of("duration", "PT3M")))));
      ReflectionTestUtils.setField(service, "webClient", WebClient.builder()
          .baseUrl("https://www.googleapis.com")
          .exchangeFunction(request -> Mono.just(ClientResponse.create(HttpStatus.OK)
              .header("Content-Type", "application/json")
              .body(request.url().getPath().endsWith("/search") ? search : details).build())).build());
      var result = service.searchTrack(track, mock(Platform.class));
      if (channel.equals("Unrelated Uploader")) assertNull(result);
      else assertEquals("https://music.youtube.com/watch?v=candidate", result.getUrl());
    }
  }

  @Test
  void acceptsOfficialLyricVideoOnArtistChannelButRejectsFanUploadsAndOtherVersions() throws Exception {
    String title = "Mrs. GREEN APPLE「soFt-dRink」Official Lyric Video";
    assertFalse(YoutubeTrackService.isUnsupportedSourceVideo(title, "Mrs. GREEN APPLE"));
    assertTrue(YoutubeTrackService.isUnsupportedSourceVideo(title, "Fan Lyrics"));
    assertTrue(YoutubeTrackService.isUnsupportedSourceVideo(
        "Mrs. GREEN APPLE - soFt-dRink Lyrics", "Mrs. GREEN APPLE"));
    assertTrue(YoutubeTrackService.isUnsupportedSourceVideo(
        "Mrs. GREEN APPLE「soFt-dRink (Live)」Official Lyric Video", "Mrs. GREEN APPLE"));
    assertEquals(new YoutubeTrackService.SourceMetadata("soFt-dRink", "Mrs. GREEN APPLE"),
        YoutubeTrackService.extractSourceMetadata(title, "Mrs. GREEN APPLE"));

    TrackRepository repository = mock(TrackRepository.class);
    YoutubeTrackService service = new YoutubeTrackService(repository, mock(AppleTrackService.class));
    String response = new ObjectMapper().writeValueAsString(Map.of("items", List.of(Map.of(
        "snippet", Map.of("categoryId", "10", "liveBroadcastContent", "none",
            "title", title, "channelTitle", "Mrs. GREEN APPLE", "description", ""),
        "contentDetails", Map.of("duration", "PT3M")))));
    ReflectionTestUtils.setField(service, "webClient", jsonClient(response));
    Track result = service.getTrackFromUrl("https://music.youtube.com/watch?v=vt9YVvYFitg&si=example");
    assertEquals("soFt-dRink", result.getTitle());
    assertEquals("Mrs. GREEN APPLE", result.getArtist());
    verify(repository).save(result);
  }

  private static final String COMPILATION_DESCRIPTION = """
      썸네일: 핀터레스트
      0:00 Je te laisserai des mots - Patrick Watson
      2:42 rises the moon - Liana Flores
      5:25 Here Comes a Thought(slowed) - Steven Universe
      9:13 Space Song - BeachHouse
      14:33 Roslyn - Bon Iver & St. Vincent
      """;

  @Test
  void detectsCompilationTitlesAndMultipleSongTimestamps() {
    assertTrue(YoutubeTrackService.isMusicCompilation("꿈", COMPILATION_DESCRIPTION));
    assertTrue(YoutubeTrackService.isMusicCompilation("𝐏𝐥𝐚𝐲𝐥𝐢𝐬𝐭 | 여름", null));
    assertTrue(YoutubeTrackService.isMusicCompilation("잔잔한 음악 모음", null));
    assertTrue(YoutubeTrackService.isMusicCompilation("Artist - Full Album", null));
    assertTrue(YoutubeTrackService.isMusicCompilation("꿈", "Tracklist\n0:00 First song\n3:00 Second song"));
  }

  @Test
  void acceptsSingleSongsWithoutTreatingChaptersOrPromotionalLinksAsCompilations() {
    assertFalse(YoutubeTrackService.isMusicCompilation(null, null));
    assertFalse(YoutubeTrackService.isMusicCompilation("아이유 - 밤편지 Official Music Video",
        "My playlist: https://youtube.com/playlist?list=example\n0:00 Intro\n0:30 Verse\n1:00 Chorus"));
    assertFalse(YoutubeTrackService.isMusicCompilation("꿈", "0:00 Song - Artist"));
    assertFalse(YoutubeTrackService.isMusicCompilation("꿈", "0:00 Song - Artist\n0:00 Song - Artist"));
    assertFalse(YoutubeTrackService.isMusicCompilation("꿈", "0:00 Song - Artist\n3:00 Song - Artist"));
  }

  @Test
  void extractsOnlyExplicitArtistTitleFormatsWithoutDiscardingPartsOfTitles() {
    assertEquals(new YoutubeTrackService.SourceMetadata("밤편지", "IU"),
        YoutubeTrackService.extractSourceMetadata("[MV] IU - 밤편지", "1theK"));
    assertEquals(new YoutubeTrackService.SourceMetadata("밤편지", "아이유"),
        YoutubeTrackService.extractSourceMetadata("아이유 - 밤편지 Official Music Video", "1theK"));
    assertEquals(new YoutubeTrackService.SourceMetadata("문득(eternal)", "윤지영(Yoon Jiyoung)"),
        YoutubeTrackService.extractSourceMetadata(
            "[MV] 윤지영(Yoon Jiyoung) - 문득(eternal) / Official Music Video", "POCLANOS"));
    assertEquals(new YoutubeTrackService.SourceMetadata("밤편지 (Live)", "아이유"),
        YoutubeTrackService.extractSourceMetadata("아이유 - 밤편지 (Live)", "아이유 - Topic"));
    assertNull(YoutubeTrackService.extractSourceMetadata("밤편지", "가사 채널"));
    assertEquals(new YoutubeTrackService.SourceMetadata("Square's dream (네모의 꿈)", "Artist"),
        YoutubeTrackService.extractSourceMetadata("Square's dream (네모의 꿈)", "Artist - Topic"));
  }

  @Test
  void refreshesExistingYoutubeMetadataBeforeReusingIt() throws Exception {
    TrackRepository repository = mock(TrackRepository.class);
    Track existing = new Track("MV", "1theK", null, "https://music.youtube.com/watch?v=15DI60dGMMo");
    when(repository.findFirstBySourceUrl(existing.getSourceUrl())).thenReturn(Optional.of(existing));
    YoutubeTrackService service = new YoutubeTrackService(repository, mock(AppleTrackService.class));
    String response = new ObjectMapper().writeValueAsString(Map.of("items", List.of(Map.of(
        "snippet", Map.of("categoryId", "10", "liveBroadcastContent", "none",
            "title", "IU - 밤편지", "channelTitle", "1theK", "description", ""),
        "contentDetails", Map.of("duration", "PT4M13S")))));
    ReflectionTestUtils.setField(service, "webClient", jsonClient(response));

    Track refreshed = service.getTrackFromUrl(existing.getSourceUrl());

    assertSame(existing, refreshed);
    assertEquals("밤편지", refreshed.getTitle());
    assertEquals("IU", refreshed.getArtist());
    assertEquals(253_000, refreshed.getDurationMs());
    verify(repository).save(existing);
  }

  @Test
  void rejectsReportedVideoBeforeDatabaseAccessAndReturnsBadRequestMessage() throws Exception {
    TrackRepository repository = mock(TrackRepository.class);
    YoutubeTrackService service = new YoutubeTrackService(repository, mock(AppleTrackService.class));
    String response = new ObjectMapper().writeValueAsString(Map.of("items", List.of(Map.of(
        "snippet", Map.of("categoryId", "10", "liveBroadcastContent", "none",
            "title", "꿈", "channelTitle", "Sea Pearl", "description", COMPILATION_DESCRIPTION),
        "contentDetails", Map.of("duration", "PT19M43S")))));
    ReflectionTestUtils.setField(service, "webClient", jsonClient(response));
    ReflectionTestUtils.setField(service, "apiKey", "test-key");

    IllegalArgumentException error = assertThrows(IllegalArgumentException.class,
        () -> service.getTrackFromUrl("https://music.youtube.com/watch?v=15DI60dGMMo"));

    verifyNoInteractions(repository);
    var result = new GlobalExceptionHandler().handleIllegalArgument(error);
    assertEquals(HttpStatus.BAD_REQUEST, result.getStatusCode());
    assertFalse(result.getBody().isSuccess());
    assertEquals("해당 링크는 음악 모음 영상이므로 통합 링크를 만들 수 없습니다.", result.getBody().getMessage());
  }

  @Test
  void acceptsOnlyNonLiveMusicCategorySourceVideos() {
    assertTrue(YoutubeTrackService.isAcceptedSourceVideo("10", "none"));
    assertTrue(YoutubeTrackService.isAcceptedSourceVideo("24", "none"));
    assertFalse(YoutubeTrackService.isAcceptedSourceVideo("10", "live"));
    assertFalse(YoutubeTrackService.isAcceptedSourceVideo("22", "none"));
  }

  @Test
  void requiresCandidateTitleToMatchTrackTitle() {
    assertTrue(TrackMatchVerifier.hasMatchingTitleAndArtist("밤편지", "아이유", "밤편지", "아이유"));
    assertFalse(TrackMatchVerifier.hasMatchingTitleAndArtist("밤편지", "아이유", "아이유 좋은 날", "아이유"));
  }

  @Test
  void rejectsCandidateWithIncompatibleDuration() {
    assertTrue(YoutubeTrackService.hasCompatibleDuration(210_000, 220_000L));
    assertFalse(YoutubeTrackService.hasCompatibleDuration(210_000, 241_000L));
  }

  @Test
  void requiresKnownDurationsAndDoesNotTreatWordFragmentsAsNoise() {
    assertFalse(YoutubeTrackService.hasCompatibleDuration(210_000, null));
    assertTrue(YoutubeTrackService.hasCompatibleDuration(210_000, 235_000L));
  }

  private WebClient jsonClient(String response) {
    return WebClient.builder().exchangeFunction(request -> Mono.just(
        ClientResponse.create(HttpStatus.OK).header("Content-Type", "application/json")
            .body(response).build())).build();
  }
}
